
name: Build and Unit Test

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
      - 'docs/**'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Requirements
      run: sudo apt-get install -y clang-14 libc++-14-dev libc++abi-14-dev
      
    - name: Checkout mp
      uses: actions/checkout@v2
      with:
        repository: cpp-core/mp
        path: mp
        submodules: recursive
        
    - name: Build and run the tests
      run: |
        export CC=clang-14
        export CXX=clang++-14
        mkdir -p mp/build && pushd mp/build
        cmake -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/opt ..
        make -j4
        make -j4 check
        make install
        popd
